steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-backend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-frontend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gestion-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'sermaluc-gestion-servicios:us-central1:nomina-sql'
      - '--set-secrets'
      - 'DATABASE_URL=backend-database-url:latest,GOOGLE_SERVICE_ACCOUNT_KEY=google-service-account-key:latest'
      - '--set-env-vars'
      - 'FRONTEND_URL=$$FRONTEND_URL'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gestion-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=$$NEXT_PUBLIC_API_URL'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-backend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-backend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-frontend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sermaluc-apps/gestion-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

